# -*- coding: utf-8 -*-
"""atividade 6 - TT002.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oc2mHff0X-hEwteCP87KOV2Uqj6ztKqA
"""

from PIL import Image

img = Image.new("RGB",(1001,1001),"white")

img.save("Brasil.png")

def criarmatriz():
  file = open("coordenadas.txt","r")
  coordenadas = file.read().splitlines()
  file.close()
  for x in range(0,len(coordenadas)):
    coordenadas[x] = coordenadas[x].split(';')
    coordenadas[x][3]= float(coordenadas[x][3])
    coordenadas[x][4]= float(coordenadas[x][4])
  return coordenadas

def normalizar(x,min,max):
  z = (x-min)/(max-min)
  return z

latitude =[]
longitude = []
for linha in criarmatriz():
  latitude.append(linha[3])
  longitude.append(linha[4])
for x in range(0,len(latitude)):
  latitude[x] = abs(normalizar(latitude[x],0,1000))*10000 + 100
  longitude[x] = abs(normalizar(longitude[x],0,1000))*10000 + 101

img = Image.new("RGB",(1001,1001),"white")
pixeis = img.load()

R = 132
G = 245
B = 66

cor = (R,G,B)

for x in range(0,len(latitude)):
 pixeis[latitude[x],longitude[x]] = cor

img.save("Brasil.png")